import { expect, test, type Page } from "@playwright/test";
async function login(page:Page,role="admin") { await page.goto("/login"); await page.getByLabel("Email",{exact:true}).fill(`${role}@example.test`); await page.getByLabel("Password",{exact:true}).fill("synthetic-password"); await page.getByRole("button",{name:"Sign in",exact:true}).click(); await expect(page.getByRole("heading",{name:"Workspace",exact:true})).toBeVisible(); }
async function module(page:Page,name:string) { if(await page.locator("nav").isHidden()) await page.getByRole("button",{name:"Toggle navigation"}).click(); await page.locator("nav").getByRole("button",{name,exact:true}).click(); }
const detail=(page:Page)=>page.getByRole("region",{name:"MVP record details"});
const editor=(page:Page,name:string)=>page.getByRole("region",{name});
async function upload(page:Page,source:string) {await page.getByLabel("CSV file").setInputFiles({name:"assets.csv",mimeType:"text/csv",buffer:Buffer.from(source)}); await page.getByRole("button",{name:"Validate and preview",exact:true}).click();}
const origin={Origin:"http://127.0.0.1:3130"};

test("CSV preview, structured errors, confirmation and lost-response safe retry",async({page})=>{
 await login(page);await module(page,"Assets");await page.getByRole("button",{name:"Import Assets",exact:true}).click();
 await upload(page,"customer_reference,asset_type,serial_number\n1001,Device,DUP\n1001,Device,DUP\n");await expect(page.getByRole("listitem").filter({hasText:"Serial number repeats in this file."})).toBeVisible(); const download=page.waitForEvent("download");await page.getByRole("button",{name:"Download error report"}).click();expect((await download).suggestedFilename()).toBe("asset-import-errors.json");
 const serial=`IMPORT-${Date.now()}`;await upload(page,`customer_reference,asset_type,serial_number\n1001,Imported Device,${serial}\n1001,Blank Serial Device,\n`);await expect(page.getByRole("heading",{name:"2 rows · Ready for confirmation"})).toBeVisible();await expect(page.getByRole("button",{name:"Confirm import",exact:true})).toBeDisabled();await page.getByRole("checkbox").check();
 let calls=0;const keys:string[]=[];await page.route("**/api/backend/assets/import/commit",async route=>{keys.push(route.request().postDataJSON().idempotency_key);const response=await route.fetch();if(calls++===0)await route.fulfill({status:502,json:{detail:"Synthetic lost response"}});else await route.fulfill({response});});
 await page.getByRole("button",{name:"Confirm import",exact:true}).click();await expect(page.getByRole("button",{name:"Retry same import safely"})).toBeVisible();await page.getByRole("button",{name:"Retry same import safely"}).click();await expect(page.getByRole("status")).toHaveText("Import completed. Assets refreshed.");await expect(page.getByRole("button",{name:new RegExp("^#.*"+serial)})).toBeVisible();expect(keys[0]).toBe(keys[1]);const rows=await (await page.request.get("/api/backend/assets")).json();expect(rows.filter((r:{serial_number:string})=>r.serial_number===serial)).toHaveLength(1);expect(rows.filter((r:{asset_type:string})=>r.asset_type==="Blank Serial Device")).toHaveLength(1);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole("heading",{name:"Assets",exact:true}).click();await page.screenshot({path:test.info().outputPath("import-mobile.png"),fullPage:true});
});

test("Inventory CRUD, transaction record-only semantics and technician direct balance",async({page})=>{
 await login(page);await module(page,"Inventory");await page.getByRole("button",{name:"+ Add Inventory Item",exact:true}).click();const form=editor(page,"Create Inventory Item");await form.getByLabel("Item name",{exact:true}).fill("MVP Part");await form.getByLabel("Warehouse quantity",{exact:true}).fill("12");await form.getByLabel("Cost price",{exact:true}).fill("3.25");await form.getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page).getByRole("heading",{name:"MVP Part",exact:true})).toBeVisible();const item=new URL(page.url()).searchParams.get("record");
 await detail(page).getByRole("button",{name:"Edit Inventory Item"}).click();await editor(page,"Edit Inventory Item").getByLabel("Minimum limit",{exact:true}).fill("2");await editor(page,"Edit Inventory Item").getByRole("button",{name:"Save",exact:true}).click();await page.reload();await expect(detail(page)).toContainText("MVP Part");
 await page.getByRole("button",{name:"Transactions",exact:true}).click();await page.getByRole("button",{name:"+ Add Transaction",exact:true}).click();const transaction=editor(page,"Create Transaction");await transaction.getByLabel("Inventory item",{exact:true}).selectOption({label:"MVP Part"});await transaction.getByLabel("Quantity",{exact:true}).fill("2");await transaction.getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page).getByRole("heading",{name:/IN · MVP Part/})).toBeVisible();expect((await (await page.request.get(`/api/backend/inventory/${item}`)).json()).quantity).toBe(12);
 await page.getByRole("button",{name:"Technician Stock",exact:true}).click();await page.getByRole("button",{name:"+ Add Technician Stock",exact:true}).click();const stock=editor(page,"Create Technician Stock");await stock.getByLabel("Inventory item",{exact:true}).selectOption({label:"MVP Part"});await stock.getByLabel("Technician",{exact:true}).selectOption({label:"Synthetic Technician"});await stock.getByLabel("Technician quantity",{exact:true}).fill("4");await stock.getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page).getByRole("heading",{name:"Synthetic Technician · MVP Part",exact:true})).toBeVisible();await detail(page).getByRole("button",{name:"Edit Technician Stock"}).click();await editor(page,"Edit Technician Stock").getByLabel("Technician quantity",{exact:true}).fill("5");await editor(page,"Edit Technician Stock").getByRole("button",{name:"Save",exact:true}).click();await page.reload();await expect(detail(page).getByRole("heading",{name:"Synthetic Technician · MVP Part",exact:true})).toBeVisible();expect((await (await page.request.get(`/api/backend/inventory/${item}`)).json()).quantity).toBe(12);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath("inventory-mobile.png"),fullPage:true});await page.getByRole("button",{name:"Items",exact:true}).click();await page.getByRole("region",{name:"MVP records"}).getByRole("button",{name:"MVP Part",exact:true}).click();await detail(page).getByRole("button",{name:"Delete Inventory Item"}).click();await page.getByRole("button",{name:"Confirm delete"}).click();await expect(detail(page)).toContainText("Select a record");expect((await page.request.get(`/api/backend/inventory/${item}`)).status()).toBe(404);
});

test("Invoice backend total, payments, relationships and Active expense profitability",async({page})=>{
 await login(page);await module(page,"Invoices");await page.getByRole("button",{name:"+ Add Invoice",exact:true}).click();const invoice=editor(page,"Create Invoice");await invoice.getByLabel("Customer",{exact:true}).selectOption({label:"#1001 · Synthetic Customer"});await invoice.getByLabel("Work Order (optional)",{exact:true}).selectOption({label:"#1 · Synthetic Order"});await invoice.getByLabel("Invoice number",{exact:true}).fill("MVP-001");await invoice.getByLabel("Issue date",{exact:true}).fill("2026-10-05");await invoice.getByLabel("Subtotal",{exact:true}).fill("100");await invoice.getByLabel("Discount",{exact:true}).fill("10");await invoice.getByLabel("Tax",{exact:true}).fill("5");await invoice.getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page).getByRole("heading",{name:"MVP-001",exact:true})).toBeVisible();const invoiceId=new URL(page.url()).searchParams.get("record");expect((await (await page.request.get(`/api/backend/invoices/${invoiceId}`)).json()).total).toBe("95.00");await detail(page).getByRole("button",{name:"Edit Invoice",exact:true}).click();const edit=editor(page,"Edit Invoice");await edit.getByLabel("Status",{exact:true}).fill("Sent");await edit.getByLabel("Paid amount",{exact:true}).fill("50");await edit.getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page)).toContainText("Sent");await detail(page).getByRole("button",{name:"#1 · Synthetic Order",exact:true}).click();await expect(page.getByRole("heading",{name:"Work Orders",exact:true})).toBeVisible();
 await module(page,"Expenses");await page.getByRole("button",{name:"+ Add Expense",exact:true}).click();const expense=editor(page,"Create Expense");await expense.getByLabel("Category",{exact:true}).fill("MVP Travel");await expense.getByLabel("Amount",{exact:true}).fill("20");await expense.getByLabel("Expense date",{exact:true}).fill("2026-10-05");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath("expense-editor-mobile.png"),fullPage:true});await expense.getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page).getByRole("heading",{name:/MVP Travel/})).toBeVisible();const expenseId=new URL(page.url()).searchParams.get("record");let summary=await (await page.request.get("/api/backend/profitability/summary")).json();expect(summary.net_profit).toBe("75.00");await detail(page).getByRole("button",{name:"Edit Expense"}).click();await editor(page,"Edit Expense").getByLabel("Status",{exact:true}).fill("Inactive");await editor(page,"Edit Expense").getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page)).toContainText("Inactive");summary=await (await page.request.get("/api/backend/profitability/summary")).json();expect(summary.net_profit).toBe("95.00");
 await detail(page).getByRole("button",{name:"Edit Expense"}).click();await editor(page,"Edit Expense").getByLabel("Status",{exact:true}).fill("Active");await editor(page,"Edit Expense").getByRole("button",{name:"Save",exact:true}).click();await expect(detail(page)).toContainText("Active");
 await page.setViewportSize({width:1280,height:900});await module(page,"Reports");await expect(page.getByRole("region",{name:"Profitability report"})).toContainText("EGP 75.00");await page.getByLabel("Report start date").fill("2026-11-01");await page.getByLabel("Report end date").fill("2026-10-01");await expect(page.getByRole("region",{name:"Profitability report"}).getByRole("alert")).toContainText("End date must not precede");await page.getByLabel("Report start date").fill("2026-10-01");await page.getByLabel("Report end date").fill("2026-10-31");await expect(page.getByRole("region",{name:"Profitability report"})).toContainText("EGP 75.00");await page.getByRole("heading",{name:"Reports",exact:true}).click();await page.screenshot({path:test.info().outputPath("reports-desktop.png"),fullPage:true});
 await page.setViewportSize({width:390,height:844});for(const name of ["Invoices","Expenses","Reports","Inventory"]){await module(page,name);await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>{document.documentElement.dir="rtl";});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:test.info().outputPath(`${name}-mobile.png`),fullPage:true});await page.evaluate(()=>{document.documentElement.dir="ltr";});}
 expect(await page.locator("main").innerText()).not.toMatch(/[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}/i);
 await module(page,"Expenses");await page.getByRole("region",{name:"MVP records"}).getByRole("button",{name:/MVP Travel/}).click();await detail(page).getByRole("button",{name:"Delete Expense"}).click();await page.getByRole("button",{name:"Confirm delete"}).click();await expect(detail(page)).toContainText("Select a record");expect((await page.request.get(`/api/backend/expenses/${expenseId}`)).status()).toBe(404);await module(page,"Invoices");await page.getByRole("region",{name:"MVP records"}).getByRole("button",{name:"MVP-001",exact:true}).click();await detail(page).getByRole("button",{name:"Delete Invoice"}).click();await page.getByRole("button",{name:"Confirm delete"}).click();await expect(detail(page)).toContainText("Select a record");
});

test("permissions, tenant isolation and real error states",async({page})=>{
 await login(page,"technician");await module(page,"Inventory");await expect(page.getByRole("button",{name:/Add Inventory/})).toHaveCount(0);expect((await page.request.post("/api/backend/inventory",{headers:origin,data:{item_name:"Forbidden"}})).status()).toBe(403);await module(page,"Assets");await expect(page.getByRole("button",{name:"Import Assets",exact:true})).toHaveCount(0);expect((await page.request.post("/api/backend/assets/import/validate",{headers:origin,data:{csv:""}})).status()).toBe(403);const items=await (await page.request.get("/api/backend/inventory")).json();const item=items[0].id;await page.getByRole("button",{name:"Sign out",exact:true}).click();await login(page,"foreign");await module(page,"Inventory");await expect(page.getByRole("heading",{name:"No records found"})).toBeVisible();expect((await page.request.get(`/api/backend/inventory/${item}`)).status()).toBe(404);expect((await page.request.patch(`/api/backend/inventory/${item}`,{headers:origin,data:{quantity:999}})).status()).toBe(404);await page.route("**/api/backend/inventory",route=>route.fulfill({status:503,json:{detail:"Synthetic unavailable"}}));await page.reload();await expect(page.getByRole("heading",{name:"Unable to load"})).toBeVisible();
});

test("CSV commit revalidation reports errors without partial creation",async({page})=>{
 await login(page);await module(page,"Assets");await page.getByRole("button",{name:"Import Assets",exact:true}).click();
 const serial=`RACE-${Date.now()}`;const source=`customer_reference,asset_type,serial_number\n1001,Concurrent Import,${serial}\n1001,Rollback Marker,\n`;
 await upload(page,source);await expect(page.getByRole("heading",{name:"2 rows · Ready for confirmation"})).toBeVisible();
 const customers=await(await page.request.get("/api/backend/customers")).json();
 const response=await page.request.post("/api/backend/assets",{headers:origin,data:{customer_id:customers[0].id,asset_type:"Concurrent CRUD",serial_number:serial}});expect(response.status()).toBe(201);
 const before=await(await page.request.get("/api/backend/assets")).json();
 await page.getByRole("checkbox").check();await page.getByRole("button",{name:"Confirm import",exact:true}).click();
 await expect(page.getByRole("listitem").filter({hasText:"Serial number already belongs to an Asset in your company."})).toBeVisible();
 await expect(page.getByRole("button",{name:"Confirm import",exact:true})).toHaveCount(0);
 const after=await(await page.request.get("/api/backend/assets")).json();expect(after).toHaveLength(before.length);expect(after.some((r:{asset_type:string})=>r.asset_type==="Rollback Marker")).toBe(false);
});
