"use client";
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api/client";
import type { User } from "@/lib/api/types";
import { label, useRecords, type Row } from "@/features/phase2/screens";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/states";
import { currentWeek, errorMessage, eventLabel, scheduleEventLabel, resourceFor, serviceLabel, singular, type ServiceModule } from "./contracts";
import { VisitParts } from "./visit-parts";
import { ServiceEditor } from "./editor";
import { WeekSchedule } from "./calendar";

import { requestPriorities, requestStatuses, requestValue } from "./request-values";

const workScheduleLabels:Record<string,string>={description:"Description",priority:"Priority",notes:"Notes",source:"Source",start_at:"Start",end_at:"End"};

type Navigate = (module: string, id?: string) => void;
export function ServiceScreen({ module, user, selectedId, go }: { module: ServiceModule; user: User; selectedId?: string; go: Navigate }) {
  const query = useRecords(user); const cache = useQueryClient();
  const [edit, setEdit] = useState<"new" | "edit" | null>(selectedId?.startsWith("new:") ? "new" : null);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [customerFilter, setCustomerFilter] = useState("");
  const [week, setWeek] = useState(currentWeek); const [confirmDelete, setConfirmDelete] = useState(false);
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  if (query.isPending) return <LoadingState />;
  if (query.error) return <ErrorState message={query.error.message} retry={() => { void query.refetch(); }} />;
  const data = query.data; const rows = data[resourceFor[module]]; const selected = rows.find(r => r.id === selectedId);
  const canManage = module !== "Service History" && user.permissions.includes("service:manage");
  const orders = data["work-orders"]; const order = orders.find(r => r.id === selected?.work_order_id);
  const recordName = (kind: ServiceModule, row: Row) => serviceLabel(kind, row, orders);
  const customerFor = (row: Row) => data.customers.find(c => c.id === (row.customer_id || orders.find(o => o.id === row.work_order_id)?.customer_id));
  const statusLabel=(value:unknown)=>module==="Requests"?requestValue(value,requestStatuses):String(value??"");
  const priorityLabel=(value:unknown)=>(module==="Requests"||module==="Work Orders")?requestValue(value,requestPriorities):String(value??"");
  const detailLabel=(field:string)=>(module==="Work Orders"||module==="Schedule")?workScheduleLabels[field]||field.replaceAll("_"," "):field.replaceAll("_"," ");
  const detailTime=module==="Work Orders"||module==="Schedule"?scheduleEventLabel:eventLabel;
  const statusOptions=module==="Requests"?[...requestStatuses,...Array.from(new Set(rows.map(r=>String(r.status)))).filter(value=>!requestStatuses.includes(requestValue(value,requestStatuses)))]:Array.from(new Set(rows.map(r=>String(r.status))));
  const filtered = rows.filter(r => (!status || statusLabel(r.status) === status) && (!customerFilter || customerFor(r)?.id === customerFilter) && [recordName(module, r), customerFor(r)?.name, r.description, r.notes, r.priority].join(" ").toLowerCase().includes(search.toLowerCase()));
  function selectRecord(row: Row) { setEdit(null); setConfirmDelete(false); setError(""); setNotice(""); go(module, row.id); }
  async function refresh() { await Promise.all([cache.invalidateQueries({ queryKey: ["phase2", user.id] }), cache.invalidateQueries({ queryKey: ["visit-parts", user.id] }), cache.invalidateQueries({ queryKey: ["work-order-summary", user.id] }), cache.invalidateQueries({ queryKey: ["inventory-summary", user.id] })]); }
  async function saved(id: string) { await refresh(); setEdit(null); go(module, id); }
  async function remove() { if (!selected) return; setPending(true); setError(""); try { await api(`${resourceFor[module]}/${selected.id}`, { method: "DELETE" }); await refresh(); setConfirmDelete(false); go(module); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }
  function reference(kind: string, id: unknown, title: string, collection: Row[], formatter: (row: Row) => string = label) { const row = collection.find(r => r.id === id); return <div><dt>{title}</dt><dd>{row ? <button className="text-link" onClick={() => go(kind, row.id)}>{formatter(row)}</button> : id ? "Unavailable related record" : "Not linked"}</dd></div>; }
  function related(kind: ServiceModule, collection: Row[], title = kind as string) { return <section className="service-related"><h3>{title}</h3>{collection.length ? collection.map(r => <button className="record-link" key={r.id} onClick={() => go(kind, r.id)}>{recordName(kind, r)} <span className="badge">{r.status}</span></button>) : <p>No explicitly linked records.</p>}</section>; }
  return <><div className="page-heading"><div><h1>{module === "Requests" ? "Service Requests" : module}</h1><p>{module === "Service History" ? "Explicit recorded service history and its linked records" : module === "Schedule" ? "Plan field service across seven days or browse the agenda" : "Manage field service with your existing records and team"}</p></div>{canManage && <button className="primary" onClick={() => setEdit("new")}>+ Add {singular[module]}</button>}</div>
    {edit && <ServiceEditor key={`${module}-${edit}-${selected?.id || selectedId}`} module={module} row={edit === "edit" ? selected : undefined} seed={edit === "new" && selectedId?.startsWith("new:") ? selectedId.slice(4) : undefined} data={data} user={user} close={() => { setEdit(null); if (selectedId?.startsWith("new:")) go(module); }} saved={saved} />}
    <section className="panel service-filters"><label>Search {module.toLowerCase()}<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search records or customers…" /></label><label>Filter status<select aria-label={module==="Requests"?"Filter status":undefined} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{statusOptions.map(s => <option key={s} value={s}>{module==="Requests"&&!requestStatuses.includes(s)?`Legacy: ${s}`:s}</option>)}</select></label><label>Filter customer<select value={customerFilter} onChange={e => setCustomerFilter(e.target.value)}><option value="">All customers</option>{data.customers.map(c => <option key={c.id} value={c.id}>{label(c)}</option>)}</select></label><button onClick={() => { setSearch(""); setStatus(""); setCustomerFilter(""); }}>Clear filters</button><button onClick={() => { void refresh(); }}>Refresh records</button></section>
    {module === "Schedule" && <WeekSchedule rows={filtered} orders={orders} week={week} setWeek={setWeek} select={selectRecord} />}
    <div className="records-layout service-layout"><section className="panel" aria-label={`${module} records`}><h2>{module === "Schedule" ? "All schedule records" : module === "Service History" ? "Recorded history" : "Records"}</h2>{filtered.length ? <div className="table-scroll"><table><thead><tr><th>Record</th><th>Customer</th><th>Status</th>{(module === "Requests" || module === "Work Orders") && <th>Priority</th>}</tr></thead><tbody>{filtered.map(r => <tr key={r.id} className={r.id === selected?.id ? "selected-row" : ""}><td><button className="text-link" onClick={() => selectRecord(r)}>{recordName(module, r)}</button></td><td>{label(customerFor(r))}</td><td><span className="badge">{statusLabel(r.status)}</span></td>{(module === "Requests" || module === "Work Orders") && <td>{priorityLabel(r.priority)}</td>}</tr>)}</tbody></table></div> : <EmptyState title="No records found" description="Change your filters or add a record where available." />}<p className="records-count">Showing {filtered.length} of {rows.length} records</p></section>
    <section className="panel service-detail" aria-label="Service record details">{!selected ? <EmptyState title={selectedId && !selectedId.startsWith("new:") ? "Record unavailable" : "Select a record"} description="Choose a record to see its details and service flow." /> : <><div className="profile-header"><div><h2>{recordName(module, selected)}</h2><span className="badge">{statusLabel(selected.status)}</span></div>{canManage && <div className="actions"><button onClick={() => { setEdit("edit"); setConfirmDelete(false); }}>Edit {singular[module]}</button><button onClick={() => setConfirmDelete(true)}>Delete {singular[module]}</button></div>}</div>{confirmDelete && <section className="delete-confirm" aria-label="Confirm record deletion"><h3>Delete this {singular[module].toLowerCase()}?</h3><p>{module === "Work Orders" || module === "Service Visits" ? "The backend applies its visit cancellation and installed-stock reversal rules." : "The record will be removed from the active workspace using the existing deletion rules."}</p><button disabled={pending} onClick={() => { void remove(); }}>Confirm delete</button><button disabled={pending} onClick={() => setConfirmDelete(false)}>Keep record</button></section>}
    <dl className="detail-fields">{reference("Customers", selected.customer_id || order?.customer_id, "Customer", data.customers)}{reference("Assets", selected.asset_id || (module === "Schedule" ? order?.asset_id : undefined), "Asset", data.assets)}{module === "Work Orders" && reference("Requests", selected.service_request_id, "Service Request", data["service-requests"])}{(module === "Schedule" || module === "Service Visits" || module === "Service History") && reference("Work Orders", selected.work_order_id, "Work Order", orders)}{module === "Service Visits" && reference("Schedule", selected.schedule_id, "Schedule", data.schedules, r => recordName("Schedule", r))}{module === "Service History" && reference("Service Visits", selected.service_visit_id, "Service Visit", data["service-visits"], r => recordName("Service Visits", r))}
    {(module === "Work Orders" || module === "Schedule" || module === "Service Visits" || module === "Service History") && <div><dt>Technician</dt><dd>{data.technicians.find(t => t.id === (selected.assigned_technician_id || selected.technician_id))?.display_name || ((selected.assigned_technician_id || selected.technician_id) ? "Unavailable technician" : "Unassigned")}</dd></div>}
    {["description", "priority", "source", "notes", "service_type", "summary"].filter(key => selected[key]).map(key => <div key={key}><dt>{detailLabel(key)}</dt><dd>{key==="priority"?priorityLabel(selected[key]):selected[key]}</dd></div>)}
    {["start_at", "end_at", "actual_start_at", "actual_end_at"].filter(key => selected[key]).map(key => <div key={key}><dt>{detailLabel(key)} (Cairo)</dt><dd>{detailTime(selected[key])}</dd></div>)}{module === "Service History" && <div><dt>Service date (as recorded)</dt><dd>{eventLabel(selected.service_date)}</dd></div>}
    </dl>
    {module === "Requests" && <>{canManage && <button className="primary" onClick={() => go("Work Orders", `new:${selected.id}`)}>Create Work Order</button>}{related("Work Orders", orders.filter(r => r.service_request_id === selected.id))}</>}
    {module === "Work Orders" && <>{canManage && !["Completed","Cancelled"].includes(String(selected.status)) && <div className="actions"><button className="primary" onClick={() => go("Schedule", `new:${selected.id}`)}>Add Schedule</button><button onClick={() => go("Service Visits", `new:order:${selected.id}`)}>Add Service Visit</button></div>}{related("Schedule", data.schedules.filter(r => r.work_order_id === selected.id))}{related("Service Visits", data["service-visits"].filter(r => r.work_order_id === selected.id))}{related("Service History", data["service-history"].filter(r => r.work_order_id === selected.id))}</>}
    {module === "Schedule" && <>{canManage && selected.status==="Scheduled" && !data["service-visits"].some(v=>v.schedule_id===selected.id&&v.status!=="Deleted") && <button className="primary" onClick={() => go("Service Visits", `new:schedule:${selected.id}`)}>Add Service Visit</button>}{related("Service Visits", data["service-visits"].filter(r => r.schedule_id === selected.id))}</>}
    {module === "Service Visits" && <>{related("Service History", data["service-history"].filter(r => r.service_visit_id === selected.id))}<VisitParts visit={selected} items={data.inventory} user={user} refresh={refresh}/></>}
    {error && <p role="alert">{error}</p>}<p role="status">{notice}</p></> }</section></div></>;
}
