"use client";
import { useState } from "react";
import { api, ApiError } from "@/lib/api/client";
import { errorMessage } from "@/features/phase3/contracts";
type ImportError = { row: number; column: string; code: string; message: string };
type Preview = { valid: boolean; rows: number; preview: Record<string, string | number>[]; errors: ImportError[]; token?: string; created?: number; replayed?: boolean };
export function download(name: string, contents: string, type = "text/csv;charset=utf-8") { const url = URL.createObjectURL(new Blob([contents], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
export function AssetImport({ done }: { done: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [source, setSource] = useState(""); const [preview, setPreview] = useState<Preview>(); const [key, setKey] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [confirmed, setConfirmed] = useState(false); const [uncertain, setUncertain] = useState(false); const [complete, setComplete] = useState(false);
  async function validate() { setPending(true); setError(""); setConfirmed(false); try { setPreview(await api<Preview>("assets/import/validate", { method: "POST", body: JSON.stringify({ csv: source }) })); setKey(crypto.randomUUID()); } catch(e) { setError(errorMessage(e)); } finally { setPending(false); } }
  async function commit() { setPending(true); setError(""); setUncertain(true); try { const result = await api<Preview>("assets/import/commit", { method: "POST", body: JSON.stringify({ csv: source, token: preview?.token, idempotency_key: key }) }); if (result.valid) { await done(); setComplete(true); setUncertain(false); } else { setPreview(result); setUncertain(false); setConfirmed(false); } } catch(e) { if (e instanceof ApiError && [400,413].includes(e.status)) { setUncertain(false); setConfirmed(false); } setError(errorMessage(e)); } finally { setPending(false); } }
  return <section className="panel import-panel" aria-label="Asset CSV import"><button onClick={() => setOpen(!open)} aria-expanded={open}>Import Assets</button>{open && <><h2>Import Assets from CSV</h2><p>Create only · UTF-8 CSV · 1 MB · 1000 rows. Customer reference is the customer’s displayed number. Serial comparisons trim surrounding whitespace and remain case-sensitive; stored serial text is preserved. Existing Assets, including deleted records, reserve their serial for import.</p><button onClick={async () => { try { const template = await api<{ csv: string }>("assets/import/template"); download("asset-template.csv", template.csv); } catch(e) { setError(errorMessage(e)); } }}>Download CSV template</button><label>CSV file<input type="file" accept=".csv,text/csv" disabled={pending || uncertain} onChange={async e => { setPreview(undefined); setComplete(false); setError(""); const file = e.target.files?.[0]; if (!file) return; if (!file.name.toLowerCase().endsWith(".csv") || file.size > 1048576) { setSource(""); setError("Select a CSV file of 1 MB or smaller."); return; } try { setSource(new TextDecoder("utf-8", { fatal:true }).decode(await file.arrayBuffer())); } catch { setSource(""); setError("CSV must use UTF-8 encoding."); } }} /></label><button disabled={!source || pending || uncertain} onClick={() => { void validate(); }}>Validate and preview</button>{error && <p role="alert">{error}</p>}{complete ? <p role="status">Import completed. Assets refreshed.</p> : preview && <><h3>{preview.rows} rows · {preview.valid ? "Ready for confirmation" : "Validation errors"}</h3>{preview.errors?.length > 0 && <><button onClick={() => download("asset-import-errors.json", JSON.stringify(preview.errors, null, 2), "application/json")}>Download error report</button><ul>{preview.errors.map((e,i) => <li key={i}>Row {e.row} · {e.column}: {e.message}</li>)}</ul></>}<div className="table-scroll"><table><thead><tr><th>Row</th><th>Customer</th><th>Asset type</th><th>Serial number</th></tr></thead><tbody>{preview.preview?.map((r,i) => <tr key={i}><td>{r.row}</td><td>{r.customer}</td><td>{r.asset_type}</td><td>{r.serial_number || "None"}</td></tr>)}</tbody></table></div>{preview.valid && <><label className="check-label"><input type="checkbox" checked={confirmed} disabled={pending || uncertain} onChange={e => setConfirmed(e.target.checked)} />I confirm creation of these Assets. No existing Asset will be updated.</label><button className="primary" disabled={!confirmed || pending} onClick={() => { void commit(); }}>{pending ? "Importing…" : uncertain ? "Retry same import safely" : "Confirm import"}</button>{uncertain && <p>Keep this file and confirmation unchanged. Retry uses the same key and cannot create the same batch twice.</p>}</>}</>}</>}</section>;
}
