"use client";
import { useState } from "react";
import geography from "./geography.json";
const subdivisions:Record<string,{code:string;name:string}[]>=geography.states;
const localities:Record<string,string[]>=geography.areas;
export function AssetLocation({row}:{row?:{[key:string]:unknown}}) {
 const [country,setCountry]=useState(String(row?.country||"EG"));const [state,setState]=useState(String(row?.state||""));const [area,setArea]=useState(String(row?.area||""));
 return <section><h3>Asset location</h3><div className="form-grid"><label>Country<select aria-label="Country" name="country" value={country} onChange={e=>{setCountry(e.target.value);setState("");setArea("");}}>{geography.countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label>Governorate / State / Province<select aria-label="Governorate / State / Province" name="state" value={state} onChange={e=>{setState(e.target.value);setArea("");}}><option value="">Select state / governorate</option>{(subdivisions[country]||[]).map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label>Area / locality<input name="area" list={`asset-localities-${state}`} value={area} maxLength={150} onChange={e=>setArea(e.target.value)} /></label><datalist id={`asset-localities-${state}`}>{(country==="EG"?localities[state]||[]:[]).map(a=><option key={a} value={a}/>)}</datalist><label>Address<input name="address" maxLength={500} defaultValue={String(row?.address||"")} /></label><label>Location URL<input name="location_url" type="url" maxLength={1000} defaultValue={String(row?.location_url||"")} /></label></div><p>ISO country/subdivision reference. Egyptian locality suggestions depend on the governorate (GeoNames); enter an actual locality if absent. Other countries use free-text locality because universal maintained coverage is unavailable.</p></section>;
}
export function WarrantyFields({row}:{row?:{[key:string]:unknown}}) {
 const [installed,setInstalled]=useState(String(row?.installation_date||""));const [years,setYears]=useState(String(row?.warranty_years??""));
 let end="";if(installed&&years!==""&&Number.isInteger(Number(years))&&Number(years)>=0&&Number(years)<=100){const [y,m,d]=installed.split("-").map(Number);const last=new Date(Date.UTC(y+Number(years),m,0)).getUTCDate();end=`${String(y+Number(years)).padStart(4,"0")}-${String(m).padStart(2,"0")}-${String(Math.min(d,last)).padStart(2,"0")}`;}
 return <div className="form-grid"><label>Installation date<input name="installation_date" type="date" value={installed} onChange={e=>setInstalled(e.target.value)}/></label><label>Maintenance cycle (months)<input name="maintenance_cycle" type="number" min={1} max={1200} step={1} defaultValue={String(row?.maintenance_cycle??"")}/></label><label>Warranty period (years)<input name="warranty_years" type="number" min={0} max={100} step={1} value={years} onChange={e=>setYears(e.target.value)}/></label><div><strong>Warranty end date</strong><output aria-label="Warranty end date">{end||"Unavailable until installation date and warranty years are supplied"}</output><small>Calendar years; leap-day anniversaries use February 28 in non-leap years. The server persists the authoritative result.</small></div></div>;
}
