import { expect,test } from "@playwright/test";
import type { Page } from "@playwright/test";
async function login(page:Page){await page.goto("/login");await page.getByLabel("Email",{exact:true}).fill("admin@example.test");await page.getByLabel("Password",{exact:true}).fill("synthetic-password");await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/module=Dashboard/);await expect(page.getByRole("heading",{name:"Welcome back, Synthetic Admin",exact:true})).toBeVisible();}
async function module(page:Page,name:string){if(await page.locator("nav").isHidden())await page.getByRole("button",{name:"Toggle navigation"}).click();await page.locator("nav").getByRole("button",{name,exact:true}).click();}
async function fits(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
async function noUUID(page:Page){expect(await page.locator('main').innerText()).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);}

test("predefined, custom and legacy phone labels persist with visible Customer No.",async({page})=>{
  await login(page);await module(page,"Customers");await page.getByRole("button",{name:"+ Add Customer",exact:true}).click();
  const form=page.getByRole("region",{name:"Create customer"});await form.getByLabel("Name",{exact:true}).fill("Label UX Customer");await form.getByLabel("Phone",{exact:true}).fill("01000000020");
  const label=form.getByLabel("Label / description 1",{exact:true});for(const name of ['Primary','Mobile','Work','Home','Office','Emergency']){await label.selectOption(name);await expect(label).toHaveValue(name);}
  await label.selectOption("Work");await form.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByRole("heading",{name:"Label UX Customer",exact:true})).toBeVisible();await expect(page.locator(".profile .eyebrow")).toHaveText(/Customer No\. #\d+/);
  await page.getByRole("button",{name:"Edit Customer",exact:true}).click();let edit=page.getByRole("region",{name:"Edit customer"});await edit.getByLabel("Label / description 1",{exact:true}).selectOption("__other__");await edit.getByLabel("Custom phone label 1",{exact:true}).fill("Dispatch / legacy desk");await edit.getByRole("button",{name:"Save",exact:true}).click();await expect(page.getByText(/Dispatch \/ legacy desk:/)).toBeVisible();
  await page.reload();await page.getByRole("button",{name:"Edit Customer",exact:true}).click();edit=page.getByRole("region",{name:"Edit customer"});await expect(edit.getByLabel("Custom phone label 1",{exact:true})).toHaveValue("Dispatch / legacy desk");await expect(edit.getByLabel("Label / description 1",{exact:true})).toHaveValue("__other__");
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.dir="rtl";});await fits(page);await noUUID(page);await page.screenshot({path:test.info().outputPath("phone-label-390-rtl.png"),fullPage:true});
  await edit.getByRole("button",{name:"Save",exact:true}).click();await page.getByRole("button",{name:"Edit Customer",exact:true}).click();await expect(edit.getByLabel("Custom phone label 1",{exact:true})).toHaveValue("Dispatch / legacy desk");
});

test("combined Arabic CSV mapping, inline geography correction, grouping and explicit import",async({page})=>{
  await page.setViewportSize({width:1440,height:900});await login(page);await module(page,"Assets");await page.getByRole("button",{name:"Import Data",exact:true}).click();const wizard=page.getByRole("region",{name:"Smart Import"});
  await expect(wizard.getByLabel("Import type",{exact:true})).toHaveValue("combined");const download=page.waitForEvent("download");await wizard.getByRole("button",{name:"Download Excel Template",exact:true}).click();await expect((await download).suggestedFilename()).toBe("axyrel-combined-template.xlsx");
  const serial="SMART-"+Date.now();const source=`اسم العميل,الموبايل,نوع الجهاز,Serial Number,Country,المحافظة,المنطقة,Installation Date,Maintenance Cycle,Warranty Years,Unusual,Ignore me\nWizard Customer,01000000021,Filter,${serial}-1,Egypt,Cairoo,Nasr City,2024-02-29,6,1,Acme,ignore\nWizard Customer,01000000021,Filter,${serial}-2,Egypt,Cairo,Nasr City,2024-02-29,6,1,Acme,ignore\n`;
  await wizard.getByLabel("Spreadsheet file",{exact:true}).setInputFiles({name:"customers-assets.csv",mimeType:"text/csv",buffer:Buffer.from(source)});
  await expect(wizard.getByLabel("Map اسم العميل",{exact:true})).toHaveValue("customer_name");await expect(wizard.getByLabel("Map الموبايل",{exact:true})).toHaveValue("phone");await expect(wizard.getByLabel("Map نوع الجهاز",{exact:true})).toHaveValue("asset_type");await expect(wizard.getByLabel("Map Ignore me",{exact:true})).toHaveValue("");await wizard.getByLabel("Map Unusual",{exact:true}).selectOption("manufacturer");
  await fits(page);await noUUID(page);await page.screenshot({path:test.info().outputPath("mapping-desktop.png"),fullPage:true});await page.setViewportSize({width:390,height:844});await fits(page);await page.screenshot({path:test.info().outputPath("mapping-390.png"),fullPage:true});await page.setViewportSize({width:1440,height:900});await wizard.getByRole("button",{name:"Review import",exact:true}).click();await expect(wizard.getByRole("region",{name:"Row 2 errors"})).toContainText('Cairoo');await wizard.getByText("Correct row 2",{exact:true}).click();await wizard.getByLabel("Row 2 Governorate / State",{exact:true}).selectOption("EG-C");await wizard.getByRole("button",{name:"Recheck corrections",exact:true}).click();await expect(wizard.getByRole("heading",{name:"Ready to import",exact:true})).toBeVisible();await expect(wizard.getByText("1 new Customers",{exact:true})).toBeVisible();await expect(wizard.getByText("2 new Assets",{exact:true})).toBeVisible();
  await page.screenshot({path:test.info().outputPath("review-desktop.png"),fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.dir="rtl";});await fits(page);await noUUID(page);await page.screenshot({path:test.info().outputPath("review-390-rtl.png"),fullPage:true});
  await wizard.getByRole("button",{name:"Continue to Import",exact:true}).click();await expect(wizard.getByRole("button",{name:"Confirm import",exact:true})).toBeDisabled();await wizard.getByRole("checkbox").check();await wizard.getByRole("button",{name:"Confirm import",exact:true}).click();await expect(wizard.getByRole("status")).toContainText("Import completed");await expect(wizard.getByRole("status")).toContainText("1 new Customers");await expect(wizard.getByRole("status")).toContainText("2 new Assets");await expect(page.locator(".kpi").filter({hasText:"Total Assets"})).toContainText("3");await noUUID(page);await fits(page);await page.screenshot({path:test.info().outputPath("receipt-390-rtl.png"),fullPage:true});
});

test("XLSX upload, customers-only and assets-only existing match, origin guards",async({page})=>{
  await login(page);await module(page,"Customers");await page.getByRole("button",{name:"Import Data",exact:true}).click();const wizard=page.getByRole("region",{name:"Smart Import"});await wizard.getByLabel("Import type",{exact:true}).selectOption("customers");
  const workbook=await page.evaluate(async()=>{const response=await fetch('/api/backend/imports/template?mode=customers&format=xlsx');return response.json();});
  // Create a real workbook via the approved Python dependency, never a browser XLSX library.
  const {execFileSync}=await import("node:child_process");const source=execFileSync("../.venv/Scripts/python.exe",["-c","import io,base64; from openpyxl import Workbook; w=Workbook(); w.active.append(['Name','Phone','Phone Label']); w.active.append(['Synthetic Customer','01000000001','Office']); b=io.BytesIO(); w.save(b); print(base64.b64encode(b.getvalue()).decode())"],{windowsHide:true}).toString().trim();expect(workbook.filename).toBe("axyrel-customers-template.xlsx");
  await wizard.getByLabel("Spreadsheet file",{exact:true}).setInputFiles({name:"customers.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:Buffer.from(source,"base64")});await wizard.getByRole("button",{name:"Review import",exact:true}).click();await expect(wizard.getByText("Existing customer found · Customer will NOT be duplicated",{exact:true})).toBeVisible();await expect(wizard.getByText("0 new Customers",{exact:true})).toBeVisible();await wizard.getByRole("button",{name:"Continue to Import",exact:true}).click();await wizard.getByRole("checkbox").check();await wizard.getByRole("button",{name:"Confirm import",exact:true}).click();await expect(wizard.getByRole("status")).toContainText("Import completed");
  await wizard.getByRole("button",{name:"Start another import",exact:true}).click();await wizard.getByLabel("Import type",{exact:true}).selectOption("assets");await wizard.getByLabel("Spreadsheet file",{exact:true}).setInputFiles({name:"assets.csv",mimeType:"text/csv",buffer:Buffer.from(`Name,Phone,Asset Type,Serial Number\nSynthetic Customer,01000000001,Filter,ASSETS-ONLY-${Date.now()}\n`)});await wizard.getByRole("button",{name:"Review import",exact:true}).click();await expect(wizard.getByText("0 new Customers",{exact:true})).toBeVisible();await expect(wizard.getByText("1 existing Customers matched",{exact:true})).toBeVisible();await noUUID(page);await wizard.getByRole("button",{name:"Continue to Import",exact:true}).click();await wizard.getByRole("checkbox").check();await wizard.getByRole("button",{name:"Confirm import",exact:true}).click();await expect(wizard.getByRole("status")).toContainText("1 new Assets");
  expect((await page.request.post('/api/backend/imports/preview',{headers:{Origin:'https://foreign.example'},data:{mode:'customers'}})).status()).toBe(403);
  expect((await page.request.get('/api/backend/imports/not-allowed')).status()).toBe(404);
});
