import { expect, test, type Page } from "@playwright/test";
import { execFileSync } from "node:child_process";

const detail=(page:Page)=>page.getByRole('region',{name:'Service record details',exact:true});
const origin={Origin:`http://127.0.0.1:${process.env.AXYREL_TEST_FRONTEND_PORT||3130}`};
async function records(page:Page){return (await page.request.get('/api/backend/service-requests')).json();}

// Mutate only rows just created in this Playwright run's generated database.
function seedLegacy(id:string,priority:string,status:string){
  const script=`import sys,json,re; from pathlib import Path; from sqlalchemy import create_engine,text; from sqlalchemy.engine import make_url
sys.path.insert(0,str(Path('..').resolve()))
from backend.core.config import Settings
marker=Path('test-results')/('phase3-database.json' if sys.argv[1]=='8130' else 'phase3-database-'+sys.argv[1]+'.json')
name=json.loads(marker.read_text())['database']
assert re.fullmatch(r'axyrel_phase3_test_[0-9a-f]{32}',name)
url=make_url(Settings(_env_file=Path('../.env')).database_url)
assert url.get_backend_name()=='postgresql' and url.host in {'localhost','127.0.0.1','::1'}
engine=create_engine(url.set(database=name))
with engine.begin() as db:
 result=db.execute(text('UPDATE service_requests SET priority=:priority,status=:status WHERE id=:id'),dict(id=sys.argv[2],priority=sys.argv[3],status=sys.argv[4]))
 assert result.rowcount==1
engine.dispose()`;
  execFileSync('../.venv/Scripts/python.exe',['-B','-c',script,process.env.AXYREL_PHASE3_TEST_PORT||'8130',id,priority,status],{windowsHide:true});
}

for(const layout of [{name:'desktop',width:1440,dir:'ltr'},{name:'390',width:390,dir:'ltr'},{name:'390-rtl',width:390,dir:'rtl'}]){
  test(`Requests canonical editors, inline errors and legacy PATCH compatibility ${layout.name}`,async({page})=>{
    await page.setViewportSize({width:layout.width,height:900});await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await page.getByLabel('Password',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/module=Dashboard/);await expect(page.locator('.identity')).toBeVisible();
    await page.evaluate(dir=>{document.documentElement.dir=dir;},layout.dir);
    if(await page.locator('nav').isHidden())await page.getByRole('button',{name:'Toggle navigation'}).click();await page.locator('nav').getByRole('button',{name:'Requests',exact:true}).click();
    const customers=await(await page.request.get('/api/backend/customers')).json();const existing=customers.find((c:{display_id:number})=>c.display_id===1001);
    const response=await page.request.post('/api/backend/customers',{headers:origin,data:{name:`Dependency customer ${layout.name}`}});expect(response.status()).toBe(201);const other=await response.json();await page.getByRole('button',{name:'Refresh records',exact:true}).click();
    await page.getByRole('button',{name:'+ Add Request',exact:true}).click();let form=page.getByRole('region',{name:'Create Request',exact:true});
    await expect(form.getByRole('combobox',{name:'Priority',exact:true}).locator('option')).toHaveText(['Low','Normal','High','Urgent']);await expect(form.getByRole('combobox',{name:'Status',exact:true}).locator('option')).toHaveText(['Open','In Progress','Resolved','Closed','Cancelled']);await expect(form.getByLabel('Priority',{exact:true})).toHaveValue('Normal');await expect(form.getByLabel('Status',{exact:true})).toHaveValue('Open');
    const before=await records(page);await form.getByLabel('Notes',{exact:true}).fill('Keep valid input');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(form.getByText('Customer is required.',{exact:true})).toBeVisible();await expect(form.getByText('Title is required.',{exact:true})).toBeVisible();await expect(form.getByLabel('Customer',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(form.getByLabel('Title',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(form.getByLabel('Customer',{exact:true})).toHaveAttribute('aria-describedby','request-customer-error');await expect(form.getByLabel('Title',{exact:true})).toHaveAttribute('aria-describedby','request-title-error');expect(await records(page)).toEqual(before);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath(`requests-errors-${layout.name}.png`),fullPage:true});
    await form.getByLabel('Title',{exact:true}).fill(`Request UX ${layout.name}`);await expect(form.getByText('Title is required.',{exact:true})).toHaveCount(0);await form.getByLabel('Customer',{exact:true}).selectOption(existing.id);await expect(form.getByText('Customer is required.',{exact:true})).toHaveCount(0);await expect(form.getByLabel('Notes',{exact:true})).toHaveValue('Keep valid input');
    const assets=await(await page.request.get('/api/backend/assets')).json();const asset=assets.find((a:{serial_number:string})=>a.serial_number==='SYN-001');await form.getByLabel('Asset (optional)',{exact:true}).selectOption(asset.id);await form.getByLabel('Customer',{exact:true}).selectOption(other.id);await expect(form.getByLabel('Asset (optional)',{exact:true})).toHaveValue('');await expect(form.getByLabel('Asset (optional)',{exact:true}).locator('option')).toHaveCount(1);await form.getByLabel('Customer',{exact:true}).selectOption(existing.id);
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath(`requests-editor-${layout.name}.png`),fullPage:true});
    await form.getByRole('button',{name:'Save',exact:true}).click();await expect(detail(page)).toContainText(`Request UX ${layout.name}`);const id=new URL(page.url()).searchParams.get('record')!;let saved=(await records(page)).find((r:{id:string})=>r.id===id);expect(saved.asset_id).toBeNull();expect(saved.priority).toBe('Normal');expect(saved.status).toBe('Open');
    await detail(page).getByRole('button',{name:'Edit Request',exact:true}).click();form=page.getByRole('region',{name:'Edit Request',exact:true});await form.getByLabel('Priority',{exact:true}).selectOption('High');await form.getByLabel('Status',{exact:true}).selectOption('In Progress');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(detail(page).locator('.profile-header .badge')).toHaveText('In Progress');await page.reload();await expect(detail(page).locator('.profile-header .badge')).toHaveText('In Progress');saved=(await records(page)).find((r:{id:string})=>r.id===id);expect(saved.priority).toBe('High');
    // Cancel creates nothing and reopening restores clean defaults.
    await page.getByRole('button',{name:'+ Add Request',exact:true}).click();form=page.getByRole('region',{name:'Create Request',exact:true});await form.getByLabel('Title',{exact:true}).fill('Cancelled draft');await form.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'+ Add Request',exact:true}).click();await expect(form.getByLabel('Title',{exact:true})).toHaveValue('');await expect(form.getByLabel('Priority',{exact:true})).toHaveValue('Normal');await form.getByRole('button',{name:'Cancel',exact:true}).click();expect((await records(page)).some((r:{title:string})=>r.title==='Cancelled draft')).toBe(false);
    const legacyResponse=await page.request.post('/api/backend/service-requests',{headers:origin,data:{customer_id:existing.id,title:`Case legacy ${layout.name}`}});expect(legacyResponse.status()).toBe(201);const legacy=await legacyResponse.json();seedLegacy(legacy.id,'high','CLOSED');
    await page.goto(`/workspace?module=Requests&record=${legacy.id}`);await expect(detail(page).locator('.profile-header .badge')).toHaveText('Closed');await page.getByLabel('Filter status',{exact:true}).selectOption('Closed');const table=page.getByRole('region',{name:'Requests records',exact:true});await expect(table).toContainText(`Case legacy ${layout.name}`);await expect(page.getByLabel('Filter status',{exact:true}).locator('option')).not.toContainText(['CLOSED']);
    await detail(page).getByRole('button',{name:'Edit Request',exact:true}).click();form=page.getByRole('region',{name:'Edit Request',exact:true});await expect(form.getByLabel('Priority',{exact:true})).toHaveValue('high');await expect(form.getByLabel('Status',{exact:true})).toHaveValue('CLOSED');await expect(form.getByLabel('Priority',{exact:true}).locator('option:checked')).toContainText('Current: High');await form.getByLabel('Notes',{exact:true}).fill('Legacy unrelated edit');const patch=page.waitForRequest(r=>r.method()==='PATCH'&&r.url().endsWith(`/service-requests/${legacy.id}`));await form.getByRole('button',{name:'Save',exact:true}).click();const payload=(await patch).postDataJSON();expect(payload).not.toHaveProperty('priority');expect(payload).not.toHaveProperty('status');await expect(detail(page)).toContainText('Legacy unrelated edit');let stored=(await records(page)).find((r:{id:string})=>r.id===legacy.id);expect(stored.priority).toBe('high');expect(stored.status).toBe('CLOSED');
    await detail(page).getByRole('button',{name:'Edit Request',exact:true}).click();form=page.getByRole('region',{name:'Edit Request',exact:true});await form.getByLabel('Priority',{exact:true}).selectOption('High');await form.getByLabel('Status',{exact:true}).selectOption('Closed');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(form).toHaveCount(0);stored=(await records(page)).find((r:{id:string})=>r.id===legacy.id);expect(stored.priority).toBe('High');expect(stored.status).toBe('Closed');
    seedLegacy(legacy.id,'LOW','Awaiting parts');await page.reload();await expect(detail(page).locator('.profile-header .badge')).toHaveText('Awaiting parts');await page.getByLabel('Filter status',{exact:true}).selectOption('Awaiting parts');await expect(table).toContainText(`Case legacy ${layout.name}`);await expect(page.getByLabel('Filter status',{exact:true}).locator('option:checked')).toHaveText('Legacy: Awaiting parts');await detail(page).getByRole('button',{name:'Edit Request',exact:true}).click();form=page.getByRole('region',{name:'Edit Request',exact:true});await expect(form.getByLabel('Priority',{exact:true}).locator('option:checked')).toContainText('Current: Low');await form.getByRole('button',{name:'Cancel',exact:true}).click();
    seedLegacy(legacy.id,'critical legacy','Open');await page.reload();await detail(page).getByRole('button',{name:'Edit Request',exact:true}).click();form=page.getByRole('region',{name:'Edit Request',exact:true});await expect(form.getByLabel('Priority',{exact:true}).locator('option:checked')).toContainText('critical legacy');await form.getByLabel('Priority',{exact:true}).selectOption('Urgent');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(form).toHaveCount(0);stored=(await records(page)).find((r:{id:string})=>r.id===legacy.id);expect(stored.priority).toBe('Urgent');
    await page.evaluate(dir=>{document.documentElement.dir=dir;},layout.dir);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath(`requests-display-${layout.name}.png`),fullPage:true});
    await detail(page).getByRole('button',{name:'Delete Request',exact:true}).click();await page.getByRole('button',{name:'Keep record',exact:true}).click();expect((await page.request.get(`/api/backend/service-requests/${legacy.id}`)).status()).toBe(200);await detail(page).getByRole('button',{name:'Delete Request',exact:true}).click();await page.getByRole('button',{name:'Confirm delete',exact:true}).click();await expect(detail(page)).toContainText('Select a record');expect((await page.request.get(`/api/backend/service-requests/${legacy.id}`)).status()).toBe(404);
  });
}
