import { expect,test,type Page } from '@playwright/test';
import { execFileSync } from 'node:child_process';

const detail=(page:Page)=>page.getByRole('region',{name:'Service record details',exact:true});
const origin={Origin:`http://127.0.0.1:${process.env.AXYREL_TEST_FRONTEND_PORT||3130}`};
async function get(page:Page,resource:string,id?:string){const response=await page.request.get(`/api/backend/${resource}${id?'/'+id:''}`);expect(response.ok()).toBe(true);return response.json();}
async function post(page:Page,resource:string,data:Record<string,unknown>){const response=await page.request.post(`/api/backend/${resource}`,{headers:origin,data});expect(response.status(),await response.text()).toBe(201);return response.json();}
async function open(page:Page,module:string,id:string,dir:string){await page.goto(`/workspace?module=${encodeURIComponent(module)}&record=${id}`);await expect(detail(page).locator('.profile-header')).toBeVisible();await page.evaluate(value=>{document.documentElement.dir=value;},dir);}
async function fits(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('main').innerText()).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);}
async function screenshot(page:Page,name:string){await fits(page);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath(name+'.png'),fullPage:true});}
function seedLegacyPriority(id:string,priority:string){
  // Target only this run's generated database, never the configured app database.
  const script=`import sys,json,re; from pathlib import Path; from sqlalchemy import create_engine,text; from sqlalchemy.engine import make_url
sys.path.insert(0,str(Path('..').resolve()))
from backend.core.config import Settings
marker=Path('test-results')/('phase3-database.json' if sys.argv[1]=='8130' else 'phase3-database-'+sys.argv[1]+'.json')
name=json.loads(marker.read_text())['database']
assert re.fullmatch(r'axyrel_phase3_test_[0-9a-f]{32}',name)
url=make_url(Settings(_env_file=Path('../.env')).database_url)
assert url.get_backend_name()=='postgresql' and url.host in {'localhost','127.0.0.1','::1'}
engine=create_engine(url.set(database=name))
with engine.begin() as db:
 result=db.execute(text('UPDATE work_orders SET priority=:priority WHERE id=:id'),dict(id=sys.argv[2],priority=sys.argv[3]))
 assert result.rowcount==1
engine.dispose()`;
  execFileSync('../.venv/Scripts/python.exe',['-B','-c',script,process.env.AXYREL_PHASE3_TEST_PORT||'8130',id,priority],{windowsHide:true});
}

for(const layout of [{name:'desktop',width:1440,dir:'ltr'},{name:'390',width:390,dir:'ltr'},{name:'390-rtl',width:390,dir:'rtl'}]){
  test(`Work Order Priority and two independent Cairo schedules ${layout.name}`,async({page})=>{
    await page.setViewportSize({width:layout.width,height:900});await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill('admin@example.test');await page.getByLabel('Password',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/module=Dashboard/);await expect(page.locator('.identity')).toBeVisible();
    const customer=(await get(page,'customers')).find((r:{display_id:number})=>r.display_id===1001);const asset=(await get(page,'assets')).find((r:{serial_number:string})=>r.serial_number==='SYN-001');const other=await post(page,'customers',{name:`Schedule filter other ${layout.name}`});
    const title=`Work schedule ${layout.name}`;const request=await post(page,'service-requests',{customer_id:customer.id,asset_id:asset.id,title,description:'Work Order description',priority:'High'});
    await open(page,'Requests',request.id,layout.dir);await detail(page).getByRole('button',{name:'Create Work Order',exact:true}).click();let form=page.getByRole('region',{name:'Create Work Order',exact:true});
    await expect(form.getByRole('combobox',{name:'Priority',exact:true}).locator('option')).toHaveText(['Low','Normal','High','Urgent']);await expect(form.getByLabel('Priority',{exact:true})).toHaveValue('Normal');await expect(form.getByLabel('Status',{exact:true}).locator('option')).toHaveText(['Open','In Progress','Completed','Cancelled']);
    await expect(form.getByLabel('Customer',{exact:true})).toHaveValue(customer.id);await expect(form.getByLabel('Asset (optional)',{exact:true})).toHaveValue(asset.id);await expect(form.getByLabel('Service Request (optional)',{exact:true})).toHaveValue(request.id);await form.getByLabel('Technician (optional)',{exact:true}).selectOption({label:'Synthetic Technician'});await form.locator('textarea[name="notes"]').fill('Work Order notes');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(detail(page).getByRole('heading',{name:new RegExp(title)})).toBeVisible();const orderId=new URL(page.url()).searchParams.get('record')!;const original=await get(page,'work-orders',orderId);expect(original.priority).toBe('Normal');expect(original.service_request_id).toBe(request.id);
    seedLegacyPriority(orderId,'high');await open(page,'Work Orders',orderId,layout.dir);const legacy=await get(page,'work-orders',orderId);await expect(detail(page).locator('.detail-fields dt')).toHaveText(['Customer','Asset','Service Request','Technician','Description','Priority','Notes']);
    await detail(page).getByRole('button',{name:'Edit Work Order',exact:true}).click();form=page.getByRole('region',{name:'Edit Work Order',exact:true});await expect(form.getByLabel('Priority',{exact:true}).locator('option:checked')).toHaveText('Current: High (stored as "high")');expect(await get(page,'work-orders',orderId)).toEqual(legacy);await form.locator('textarea[name="notes"]').fill('Unrelated Work Order edit');const patch=page.waitForRequest(r=>r.method()==='PATCH'&&r.url().endsWith(`/work-orders/${orderId}`));await form.getByRole('button',{name:'Save',exact:true}).click();expect((await patch).postDataJSON()).not.toHaveProperty('priority');await expect(detail(page)).toContainText('Unrelated Work Order edit');expect((await get(page,'work-orders',orderId)).priority).toBe('high');
    await detail(page).getByRole('button',{name:'Edit Work Order',exact:true}).click();form=page.getByRole('region',{name:'Edit Work Order',exact:true});await form.getByLabel('Priority',{exact:true}).selectOption('High');await form.getByLabel('Status',{exact:true}).selectOption('In Progress');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(detail(page).locator('.profile-header .badge')).toHaveText('In Progress');await open(page,'Work Orders',orderId,layout.dir);let saved=await get(page,'work-orders',orderId);expect(saved.priority).toBe('High');expect(saved.status).toBe('In Progress');for(const field of ['customer_id','asset_id','service_request_id','assigned_technician_id'])expect(saved[field]).toBe(original[field]);
    seedLegacyPriority(orderId,'critical legacy');await open(page,'Work Orders',orderId,layout.dir);await expect(detail(page)).toContainText('critical legacy');await detail(page).getByRole('button',{name:'Edit Work Order',exact:true}).click();form=page.getByRole('region',{name:'Edit Work Order',exact:true});await expect(form.getByLabel('Priority',{exact:true}).locator('option:checked')).toContainText('critical legacy');await screenshot(page,`work-order-legacy-${layout.name}`);await form.getByLabel('Priority',{exact:true}).selectOption('Urgent');await form.getByRole('button',{name:'Save',exact:true}).click();await expect(form).toHaveCount(0);saved=await get(page,'work-orders',orderId);expect(saved.priority).toBe('Urgent');expect(saved.status).toBe('In Progress');
    const schedules:{id:string;start_at:string;end_at:string;work_order_id:string;technician_id:string}[]=[];
    for(const item of [{day:'06',start:'10:00',end:'11:30',offset:'',notes:'First schedule'},{day:'08',start:'14:00',end:'15:30',offset:'+03:00',notes:'Second schedule'}]){
      await open(page,'Work Orders',orderId,layout.dir);await detail(page).getByRole('button',{name:'Add Schedule',exact:true}).click();form=page.getByRole('region',{name:'Create Schedule',exact:true});await expect(form.getByLabel('Work Order',{exact:true})).toHaveValue(orderId);await expect(form.getByLabel('Technician (optional)',{exact:true})).toHaveValue(saved.assigned_technician_id);await expect(form.locator('[name="status"]')).toHaveValue('Scheduled');
      await expect(form.getByLabel('Start (Cairo)',{exact:true})).toHaveValue('');await expect(form.getByLabel('End (Cairo)',{exact:true})).toHaveValue('');await expect(form.locator('textarea[name="notes"]')).toHaveValue('');await form.getByLabel('Start (Cairo)',{exact:true}).fill(`2026-10-${item.day}T${item.start}`);await form.getByLabel('End (Cairo)',{exact:true}).fill(`2026-10-${item.day}T${item.end}`);await form.getByLabel('Start UTC offset (optional)',{exact:true}).fill(item.offset);await form.getByLabel('End UTC offset (optional)',{exact:true}).fill(item.offset);await form.locator('textarea[name="notes"]').fill(item.notes);await form.getByRole('button',{name:'Save',exact:true}).click();await expect(detail(page).getByRole('heading',{name:new RegExp(`Schedule.*${title}`)})).toBeVisible();const scheduleId=new URL(page.url()).searchParams.get('record')!;schedules.push(await get(page,'schedules',scheduleId));
      await expect(detail(page).locator('.detail-fields dt')).toHaveText(['Customer','Asset','Work Order','Technician','Notes','Start (Cairo)','End (Cairo)']);await expect(detail(page)).toContainText(`${item.day} Oct 2026 · ${item.start==="10:00"?"10:00 AM":"02:00 PM"}`);await expect(detail(page)).toContainText(`${item.day} Oct 2026 · ${item.end==="11:30"?"11:30 AM":"03:30 PM"}`);await expect(detail(page).getByRole('button',{name:'Add Service Visit',exact:true})).toBeVisible();
    }
    const iso=(value:string)=>new Date(/[zZ]|[+-]\d\d:\d\d$/.test(value)?value:value+'Z').toISOString();expect(iso(schedules[0].start_at)).toBe('2026-10-06T07:00:00.000Z');expect(iso(schedules[1].start_at)).toBe('2026-10-08T11:00:00.000Z');
    for(const schedule of schedules){
      await open(page,'Schedule',schedule.id,layout.dir);await detail(page).getByRole('button',{name:'Edit Schedule',exact:true}).click();form=page.getByRole('region',{name:'Edit Schedule',exact:true});await expect(form.getByLabel('Start (Cairo)',{exact:true})).toHaveValue(schedule.id===schedules[0].id?'2026-10-06T10:00':'2026-10-08T14:00');await expect(form.getByLabel('Start UTC offset (optional)',{exact:true})).toHaveValue('+03:00');await form.locator('textarea[name="notes"]').fill(`Independent edit ${schedule.id===schedules[0].id?'one':'two'}`);const edit=page.waitForRequest(r=>r.method()==='PATCH'&&r.url().endsWith(`/schedules/${schedule.id}`));await form.getByRole('button',{name:'Save',exact:true}).click();const payload=(await edit).postDataJSON();expect(payload).not.toHaveProperty('start_at');expect(payload).not.toHaveProperty('end_at');await expect(form).toHaveCount(0);await open(page,'Schedule',schedule.id,layout.dir);const after=await get(page,'schedules',schedule.id);for(const field of ['start_at','end_at','work_order_id','technician_id'])expect(after[field]).toBe(schedule[field as keyof typeof schedule]);
    }
    const synthetic=(await get(page,'work-orders')).find((r:{display_id:number})=>r.display_id===1);await post(page,'schedules',{work_order_id:synthetic.id,start_at:'2026-10-06T12:00:00+03:00',end_at:'2026-10-06T13:00:00+03:00',status:'Cancelled'});await page.getByRole('button',{name:'Refresh records',exact:true}).click();await page.getByLabel('Week starting',{exact:true}).fill('2026-10-05');await page.getByLabel('Search schedule',{exact:true}).fill(title);
    const calendar=page.getByRole('region',{name:'Seven-day schedule',exact:true});await expect(calendar.locator('.week-view > section')).toHaveCount(7);await expect(calendar.locator('.week-view h3')).toContainText(['06 Oct 2026','08 Oct 2026']);await expect(calendar.locator('.week-view .schedule-card')).toHaveCount(2);await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(2);
    const list=page.getByRole('region',{name:'Schedule records',exact:true});await expect(list).toContainText('06 Oct 2026 · 10:00 AM');await expect(list).toContainText('08 Oct 2026 · 02:00 PM');
    await page.getByRole('button',{name:'Next seven days',exact:true}).click();await expect(page.getByLabel('Week starting',{exact:true})).toHaveValue('2026-10-12');await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(0);await page.getByRole('button',{name:'Previous seven days',exact:true}).click();await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(2);
    const filters=page.locator('.service-filters select');await filters.nth(0).selectOption('Cancelled');await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(0);await filters.nth(0).selectOption('Scheduled');await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(2);await filters.nth(1).selectOption(other.id);await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(0);await filters.nth(1).selectOption(customer.id);await expect(calendar.locator('.agenda-view .schedule-card')).toHaveCount(2);if(layout.width>390)await page.getByRole('button',{name:'Agenda view',exact:true}).click();await expect(calendar.locator('.agenda-view')).toBeVisible();await expect(calendar.locator('.agenda-view')).toContainText('06 Oct 2026 · 11:30 AM');await expect(calendar.locator('.agenda-view')).toContainText('08 Oct 2026 · 03:30 PM');await screenshot(page,`schedule-agenda-${layout.name}`);
    if(layout.width>390){await page.getByRole('button',{name:'Week view',exact:true}).click();await expect(calendar.locator('.week-view')).toBeVisible();await screenshot(page,'schedule-week-desktop');}
    await open(page,'Work Orders',orderId,layout.dir);const linked=detail(page).locator('.service-related').filter({has:page.getByRole('heading',{name:'Schedule',exact:true})});await expect(linked.getByRole('button')).toHaveCount(2);await expect(linked).toContainText('06 Oct 2026 · 10:00 AM');await expect(linked).toContainText('08 Oct 2026 · 02:00 PM');await screenshot(page,`work-order-linked-schedules-${layout.name}`);await linked.getByRole('button',{name:/06 Oct 2026/}).click();await expect(page).toHaveURL(new RegExp(schedules[0].id));await expect(detail(page)).toContainText('Independent edit one');await expect(detail(page).getByRole('button',{name:new RegExp(customer.name)})).toBeVisible();await expect(detail(page).getByRole('button',{name:/SYN-001/})).toBeVisible();
    expect((await get(page,'schedules')).filter((r:{work_order_id:string})=>r.work_order_id===orderId)).toHaveLength(2);
  });
}
